name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  run-linters:
    name: run-linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install NPM Packages
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm run lint
  deploy:
    needs: run-linters
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: production
      url: ${{ steps.build-publish.outputs.page_url }}
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
        with:
          path: './storybook-static'
          build_command: npm run storybook:build
